### ISSUE TITLE
GPU related

### ISSUE THREAD

**Issue by wabyking** [kalaspuffar/tensorflow-mnist-test#2]
Can this JAVA-version Tensorflow use GPU for prediction?

**Comment by kalaspuffar** [comment]
Hi @wabyking 

Well if it's built correctly, not sure if we are able to do that on windows yet.

Then it should use the GUI bindings for the predictions. Not super important because the predictions seldom take much time. We build against the GPU library so I think we use the GPU when using the Java libraries, not verified though.

Best regards
Daniel

**Comment by wabyking** [comment]
Thank you, Daniel!
