### ISSUE TITLE
ERROR to load trained Tensorflow model

### ISSUE THREAD

**Issue by msarfrazcss** [kalaspuffar/tensorflow-mnist-test#4]
Hi,
I have followed all the steps mentioned in this tutorial to train my model, but model doesn't load in java, and gives error at the line:
**SavedModelBundle smb = SavedModelBundle.load("./waldo_model/saved_model", "serve");**

ERROR is:
Exception in thread "main" java.lang.**UnsatisfiedLinkError**: org.tensorflow.SavedModelBundle.load(Ljava/lang/String;[Ljava/lang/String;[B)Lorg/tensorflow/SavedModelBundle;
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
	at org.ea.waldo.RunInference.main(RunInference.java:53)

**I am using MACOSX, and directory structure is:**
![screen shot 2018-11-27 at 10 42 57 am](https://user-images.githubusercontent.com/43664119/49059944-5ea52280-f231-11e8-8f75-fc61eb80ea7a.png)

I run the command from project directory to train model:
**tensorflow-mnist-test-master > python mnist_train.py**
After that no .pb file generated into model directory.
Can anyone tell me please what may be the cause for this error?

**Comment by kalaspuffar** [comment]
Hi @msarfrazcss 

You are right, it can't find the saved_model file in the waldo_model directory. Your directory is called model and therefore it will not find it.

In the example, I use the model directory as a save destination but in the code, I've changed to one of the subdirectories in order to test different models.

Great catch.

In your case ```SavedModelBundle smb = SavedModelBundle.load("./model", "serve");``` should work better.

Best regards
Daniel

**Comment by msarfrazcss** [comment]
I am already using:
**SavedModelBundle smb = SavedModelBundle.load("./model", "serve");**

mnist_train.py Script does not create .pb file anywhere?

Or have i need to create subdirectory saved_model within model dir

**Comment by msarfrazcss** [comment]
Hi Daniel, thanks for your concern,
I am using below code:

Mat frame = new Mat();
this.myWebcam.read(frame);
byte[] imageBytes = new byte[(int) (frame.total() * frame.channels())];
        try (Graph graph = new Graph()) {
            GraphBuilder graphBuilder = new GraphBuilder(graph);

            final Output<Float> output =
                graphBuilder.div( // Divide each pixels with the MEAN
                    graphBuilder.resizeBilinear( // Resize using bilinear interpolation
                            graphBuilder.expandDims( // Increase the output tensors dimension
                                    graphBuilder.cast( // Cast the output to Float
                                            **graphBuilder.decodeJpeg**(graphBuilder.constant("input", imageBytes), 3), Float.class),
                                    graphBuilder.constant("make_batch", 0)),
                            graphBuilder.constant("size", new int[]{SIZE, SIZE})),
                    graphBuilder.constant("scale", MEAN));

            try (Session session = new Session(graph)) {
                return session.runner().fetch(output.op().name()).run().get(0).expect(Float.class);
            }
        }


This code can detect the object from an image, but
i want to detect the object from live webcam, to do so i am passing Mat object into it, then it giving the error like:

java.lang.IllegalArgumentException: Expected image (JPEG, PNG, or GIF), got unknown format starting with '\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000'
	 [[{{node DecodeJpeg}} = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input)]]
	at org.tensorflow.Session.run(Native Method)
	at org.tensorflow.Session.access$100(Session.java:48)
	at org.tensorflow.Session$Runner.runHelper(Session.java:314)
	at org.tensorflow.Session$Runner.run(Session.java:264)

Your help will be high appreciable if you help me to solve this issue.
Thanks once again.

**Comment by kalaspuffar** [comment]
I don't know how your webcam is encoding the stream but it seems not to be jpeg encoded.

**Comment by msarfrazcss** [comment]
Hi @kalaspuffar ,
Thanks a lot for your support,
My issue has been resolved, I converted **Mat object into BufferedImage** then pass BufferedImge object into stream to decode into Jpeg format.

**Is this way good?**
Because i am using MAC CPU, it is getting very slow on webcam, **it take 25 seconds** to process and create rectangle on webcam frame , **Can this go fast on CPU.**

**Or it is necessary to use GPU?**

**Comment by kalaspuffar** [comment]
Hi @msarfrazcss 

Great to hear, great work. I wonder if you are going over the bridge for water. Perhaps you can use the stream directly instead of encoding and decoding the images.

Streaming images are faster, and GPU is always much faster than CPU. And TPU's and NPU's are always even faster.

If you want to think of the different types of processing units you could say that a CPU is a shopping cart, well it has 4 wheels and it can go anywhere and help you transport things but not made only for speed, it's made to be able to be used for a lot of different stuff.

A GPU is a car which is made for going fast from place to place but you can still use it for most of your workflows.

TPU's and NPU's are trains, they are built for moving things and nothing else, they go on rails and require that you come to them. They are restricted but does the work of moving things extremely efficiently.

**Comment by msarfrazcss** [comment]
Hi @kalaspuffar ,
Thanks once again for your support,

How can i use stream directly, can you help me please if i share you my code?

**Comment by kalaspuffar** [comment]
Hi @msarfrazcss 

I'm not sure that I can help you there. It is probably up to the camera manufacturer what kind of stream they provide. So you need to read up on the specifics and try to implement against that specification. And as I don't have your camera and haven't tried this before I can't be of much help.

Best regards
Daniel
